version: 2.1
jobs:
  build:
    executor: node/default
    steps:
      - run:
          command: npm  insatll
  deploy:
    steps:
      - run:
          command: rsync -zvhr -e ssh . ubuntu@3.80.208.171:/var/sites/dev/node-project/
      - run:
          command: ssh ubuntu@3.80.208.171 'pm2 restart node-project'
          
workflows:
  my-workflow:
    jobs:
      - build:
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
