version: 2.1

jobs:
  build_and_test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
      - run:
          command: rsync -zvhr -e ssh . ubuntu@3.80.208.171:/var/sites/dev/node-project/
      - run:
          command: ssh ubuntu@3.80.208.171 'pm2 restart node-project'  
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
          
workflows:
  my-workflow:
    jobs:
      - build_and_test:
      
