version: 2.1

jobs:
  build_and_test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
      - run: 
          command: npm app.js
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  my-workflow:
    jobs:
      - build_and_test:
