version: 2.1
  
workflows:
  hello-world:
    jobs:
      - build
      
jobs:
 build:
  executor:
   name: node/default
   steps:
    - checkout
    - run:
        name: "Install project dependencies"
        command: scp -r -o StrictHostKeyChecking=no * ubuntu@34.238.115.96:/home/ubuntu/ 
    - run:
        ssh -o StrictHostKeyChecking=no ubuntu@54.83.108.237 \
        npm i
    - run:
        ssh -o StrictHostKeyChecking=no ubuntu@54.83.108.237 \
        pm2 restart app.js
