version: 2.1
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: |
          ssh -o StrictHostKeyChecking=no ubuntu@34.238.115.96 \
          npm  insatll
      - run:
          command: rsync -zvhr -e ssh . ubuntu@34.238.115.96:/var/sites/dev/node-project/
      - run: |
          ssh -o StrictHostKeyChecking=no ubuntu@34.238.115.96 \
          pm2 restrt app.js    
          
workflows:
  my-workflow:
    jobs:
      - build:
          
